# Generated by Django 4.0.5 on 2022-06-22 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=200)),
                ('tempo_estimado', models.TimeField(default=datetime.time(0, 30))),
                ('ativo', models.BooleanField(default=True)),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('data_hora_confirmacao', models.DateTimeField(null=True)),
                ('nome_cliente', models.CharField(max_length=70)),
                ('celular_cliente', models.CharField(max_length=14)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='barbershop.servico')),
            ],
        ),
    ]
